name: Build and Push Container Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.nickmessing.com -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build container image
        run: docker build -t harbor.nickmessing.com/library/finance-tracker:${{ github.sha }} -t harbor.nickmessing.com/library/finance-tracker:latest ./server

      - name: Push image
        run: |
          docker push harbor.nickmessing.com/library/finance-tracker:${{ github.sha }}
          docker push harbor.nickmessing.com/library/finance-tracker:latest
